---
title: "Meta analysis of differential expression results from AMP-AD (Control vs AD)"
author: "Thanneer Perumal"
date: "`r date()`"
output: html_document
---
```{r knit2synapse, eval=FALSE}
library(synapseClient)
library(knit2synapse)
synapseLogin()

knit2synapse::knitToFolderEntity(file = "./MetaAnalysis.Rmd", 
                                 parentId ="syn5569102",
                                 entityName = 'MetaAnalysis of Control vs AD from all three brain banks')
```

```{r libs, echo=FALSE, warning=FALSE, message=FALSE, include=FALSE}
## It is assumed your working directory is where this file is

# Clear R console screen output
cat("\014")  

# Load required libraries
library(CovariateAnalysis)
library(data.table)
library(tidyr)
library(plyr)
library(dplyr)
library(stringr)

library(RColorBrewer)
library(ggplot2)
library(ComplexHeatmap)

library(RankProd)
library(githubr)

library(Vennerable)
library(colorfulVennPlot)

synapseLogin()

library(doParallel)
library(foreach)

clust = makeCluster(14)
registerDoParallel(clust)

options(xtable.type="html")

knitr::opts_chunk$set(
  echo = FALSE,
  warning = FALSE,
  message = FALSE,
  error = FALSE,
  tidy = FALSE,
  cache = TRUE)
```

```{r fxns}
# Utility function for combining p-values using Fishers inverse chi-square method
fishersPvalue <- function(pvalue){
  pvalue = -2*log(pvalue, base = exp(1))
  S <- 0
  N <- dim(pvalue)[2]
  
  correlation <- WGCNA::bicor(pvalue,use = 'pairwise.complete.obs');
  
  for (i in 1:(N-1))
    for (j in (i+1):N){
      if (correlation[i,j] > 0){
        S <- S + correlation[i,j]*(3.25+0.75*correlation[i,j])
      } else if (correlation[i,j] <= 0){
        S <- S + correlation[i,j]*(3.27+0.71*correlation[i,j])
      }
    }
  
  combinedPvalue.chi <- rowSums(pvalue)*(4*N)/(4*N+2*S)
  combinedPvalue <- sapply(combinedPvalue.chi, function(x,N){
    pchisq(x, df = 2*N, lower.tail = FALSE)
  },N)
  names(combinedPvalue) = rownames(pvalue)
  
  return(combinedPvalue)
}
```

### Get covariates/sample metadata from synapse
```{r covariates}
# covariates.id = c('ROSMAP' = 'syn6114444',
#                   'MSBB' = 'syn6131421',
#                   'MAYO' = 'syn6128267')
# SVA Normalised
covariates.id = c('ROSMAP' = 'syn6129368',
                  'MSBB' = 'syn7059296',
                  'MAYO' = 'syn6128630')

covariates = lapply(covariates.id, downloadFile)

covariates$ROSMAP = covariates$ROSMAP %>%
  dplyr::select(Sampleid, msex, cogdx) %>%
  dplyr::rename(ID = Sampleid, Gender = msex, Status = cogdx) %>%
  dplyr::mutate(Gender = factor(Gender, labels = c('1' = 'MALE','2'='FEMALE')),
                Status = factor(Status, labels = c('1' = 'NCI', '2' = 'MCI', '3' = 'MCI.CI', 
                                                   '4' = 'AD', '5' = 'AD.CI', '6' = 'OD')),
                BrainRegion = 'DLPFC') %>%
  dplyr::filter(Status %in% c('NCI', 'AD'))

covariates$MSBB = covariates$MSBB %>%
  dplyr::select(SampleId, SEX, BrainRegion.Diagnosis) %>%
  tidyr::separate(BrainRegion.Diagnosis, c('BrainRegion', 'Dx'), sep = '\\.') %>%
  dplyr::rename(ID = SampleId, Gender = SEX, Status = Dx) %>%
  dplyr::mutate(Gender = factor(Gender, labels = c('M' = 'MALE','F'='FEMALE')),
                Status = factor(Status),
                BrainRegion = factor(BrainRegion, labels = c('BM_10' = 'FP', 'BM_22' = 'STG', 
                                                             'BM_36' = 'PHG', 'BM_44' = 'IFG'))) %>%
  dplyr::filter(Status %in% c('ND', 'SD'))

covariates$MAYO = covariates$MAYO %>%
  dplyr::select(ID, Gender, BrainRegion.Diagnosis) %>%
  tidyr::separate(BrainRegion.Diagnosis, c('BrainRegion', 'Dx'), sep = '\\.') %>%
  dplyr::rename(Status = Dx) %>%
  dplyr::mutate(Gender = factor(Gender, labels = c('M' = 'MALE','F'='FEMALE')),
                Status = factor(Status)) %>%
  dplyr::filter(Status %in% c('Control', 'AD'))

covariates = rbindlist(covariates, use.names = T, fill = T, idcol = 'Study')
```

### Get logCPM counts from synapse
```{r counts}
# logcpm.id = c('ROSMAP' = 'syn6114447' ,
#               'MSBB' = 'syn6131419',
#               'MAYO' = 'syn6128269')
# Get SVA adjusted data
logcpm.id = c('ROSMAP' = 'syn6129370',
              'MSBB' = 'syn7059294',
              'MAYO' = 'syn6128632')

logcpm = lapply(logcpm.id, downloadFile) %>%
  lapply(function(x){
    x = dplyr::select(x, -hgnc_symbol)
    }) %>%
  join_all(type = 'full') %>%
  dplyr::select(Gene.ID, ensembl_gene_id, one_of(covariates$ID)) 
logcpm[is.na(logcpm)] = dplyr::select(logcpm, -Gene.ID, -ensembl_gene_id) %>%
  min
```

### Get residual expression from synapse
```{r counts1}
# Get SVA adjusted data
resid.expr.id = c('ROSMAP' = 'syn6129372',
                  'MSBB' = 'syn7059289',
                  'MAYO' = 'syn6128634')

resid.expr = lapply(resid.expr.id, downloadFile) %>%
  lapply(function(x){
    x = dplyr::select(x, -hgnc_symbol)
    }) %>%
  join_all(type = 'full') %>%
  dplyr::select(Gene.ID, ensembl_gene_id, one_of(covariates$ID)) 
resid.expr[is.na(resid.expr)] = dplyr::select(resid.expr, -Gene.ID, -ensembl_gene_id) %>%
  min(na.rm=T)
```

### Download differential expression data
```{r download.data}
# diffexp.id = c('ROSMAP' = 'syn6114453',
#                'MSBB' = 'syn6131423',
#                'MAYO' = 'syn6128273')
# Get SVA adjusted differential expression
diffexp.id = c('ROSMAP' = 'syn6129374',
               'MSBB' = 'syn7059298',
               'MAYO' = 'syn6128636')

diffexp = lapply(diffexp.id, downloadFile)

diffexp$ROSMAP = diffexp$ROSMAP %>%
  filter(Comparison == 'cogdx1-cogdx4') %>%
  dplyr::select(ensembl_gene_id, logFC, P.Value, adj.P.Val) %>%
  # dplyr::select(Gene.ID, logFC, P.Value, adj.P.Val) %>%
  dplyr::mutate(Tissue = 'DLPFC', Contrast = 'NCI-AD')
   
diffexp$MSBB = diffexp$MSBB %>%
  dplyr::filter(Name == 'ND-SD') %>%
  dplyr::select(ensembl_gene_id, logFC, P.Value, adj.P.Val, BrainRegion, Name) %>%
  dplyr::mutate(BrainRegion = factor(BrainRegion, labels = c('BM_10' = 'FP', 'BM_22' = 'STG', 
                                                             'BM_36' = 'PHG', 'BM_44' = 'IFG'))) %>%
  dplyr::rename(Tissue = BrainRegion, Contrast = Name)
  
diffexp$MAYO = diffexp$MAYO %>%
  dplyr::filter(Name == 'Control-AD') %>%
  tidyr::separate(Gene.ID, c('ensembl_gene_id', 'position'), sep = '\\.') %>%
  dplyr::select(ensembl_gene_id, logFC, P.Value, adj.P.Val, BrainRegion, Name) %>%
  dplyr::rename(Tissue = BrainRegion, Contrast = Name)

diffexp = rbindlist(diffexp, use.names = T, fill = T, idcol = 'Study') 

diffexp$DE = 'NONE'
diffexp$DE[diffexp$adj.P.Val <= 0.05 & diffexp$logFC >= log2(1.2)] = 'UP'
diffexp$DE[diffexp$adj.P.Val <= 0.05 & diffexp$logFC <= -log2(1.2)] = 'DOWN'

pl = list()
for (study in c('ROSMAP', 'MSBB', 'MAYO')){
  p = filter(diffexp, Study == study) %>%
    ggplot(aes(x = logFC, y = -log10(adj.P.Val), color = DE)) 
  p = p + scale_colour_manual(values = c("green","grey", "red"))
  p = p + geom_point() + theme(legend.position = 'None')
  p = p + facet_grid(Study~.+Tissue)
  pl[[study]] = p
}
multiplot(plotlist = pl, cols = 1)
```

### Get hgnc_symbol mapping from biomaRt
```{r biomart}
# Define biomart object
mart <- useMart('ENSEMBL_MART_ENSEMBL', dataset = "hsapiens_gene_ensembl", host = 'dec2015.archive.ensembl.org')

# Query biomart
Ensemble2HGNC <- getBM(attributes = c("ensembl_gene_id", "hgnc_symbol"),
                       filters = "ensembl_gene_id", 
                       values = unique(diffexp$ensembl_gene_id),
                       mart = mart) %>%
  data.table()

# Add hgnc_symbols to the logcpm matrix
logcpm = logcpm %>%
  left_join(Ensemble2HGNC)

# Add hgnc_symbols to the resid.mat matrix
resid.expr = resid.expr %>%
  left_join(Ensemble2HGNC)

# Add hgnc_symbols to the diffexp matrix
diffexp = diffexp %>%
  left_join(Ensemble2HGNC)

diffexp$Direction = 'UP'
diffexp$Direction[diffexp$logFC < 0] = 'DOWN'

writeLines('Differentially expressed at an fdr of 0.05')
diffexp %>%
  filter(adj.P.Val <= 0.05) %>%
  group_by(Tissue, Direction) %>%
  summarise(n = length(unique(ensembl_gene_id))) %>%
  spread(Direction, n)

writeLines('Differentially expressed at an fdr of 0.05 and fold change of 1.2')
diffexp %>%
  filter(adj.P.Val <= 0.05, (logFC >= log2(1.2) | logFC <= -log2(1.2))) %>%
  group_by(Tissue, Direction) %>%
  summarise(n = length(unique(ensembl_gene_id))) %>%
  spread(Direction, n)
```

### Pathway enrichment
```{r pathway.enrichment}
# Differentially expressed in ROSMAP
## Up regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC >0, Tissue == 'DLPFC') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6x3h

## Down regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC<0, Tissue == 'DLPFC') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6x4e

# Differentially expressed in MSSM FP
## Up regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC >0, Tissue == 'FP') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6xcm

## Down regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC < 0, Tissue == 'FP') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')

# Differentially expressed in MSSM STG
## Up regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC > 0, Tissue == 'STG') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')

## Down regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC < 0, Tissue == 'STG') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')

# Differentially expressed in MSSM PHG
## Up regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC > 0, Tissue == 'PHG') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6xco

## Down regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC < 0, Tissue == 'PHG') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6xge

# Differentially expressed in MAYO CER
## Up regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC > 0, Tissue == 'CER') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: 

## Down regulated
tmp = filter(diffexp, adj.P.Val <= 0.05, logFC < 0, Tissue == 'PHG') %>%
  dplyr::left_join(Ensemble2HGNC %>% as.data.table()) %>%
  filter(hgnc_symbol != '')
### Enrichr results are here: http://amp.pharm.mssm.edu/Enrichr/enrich?dataset=6xge
```

### Meta Analysis
```{r metaanalysis}
P.Value = diffexp %>% 
  # filter(Tissue %in% c('DLPFC', 'PHG', 'TCX')) %>%
  filter(ensembl_gene_id != '') %>%
  dplyr::select(ensembl_gene_id, P.Value, Tissue, Contrast) %>%
  tidyr::unite(Tissue.Contrast, Tissue, Contrast, sep = '_') %>%
  tidyr::spread(Tissue.Contrast, P.Value)
P.Value[is.na(P.Value)] = 1

min.pval = dplyr::select(P.Value, -ensembl_gene_id) %>%
  data.matrix %>% rowMin %>%
  p.adjust(method = 'BH') %>%
  data.frame(ensembl_gene_id = P.Value$ensembl_gene_id,
             min.pval = .)

max.pval = dplyr::select(P.Value, -ensembl_gene_id) %>%
  data.matrix %>% rowMax %>%
  p.adjust(method = 'BH') %>%
  data.frame(ensembl_gene_id = P.Value$ensembl_gene_id,
             max.pval = .)

fb.pval = dplyr::select(P.Value, -ensembl_gene_id) %>%
  data.matrix %>% fishersPvalue %>%
  p.adjust(method = 'BH') %>%
  data.frame(ensembl_gene_id = P.Value$ensembl_gene_id,
             fb.pval = .)

# Rank prod based analysis
expr = resid.expr[!duplicated(resid.expr$ensembl_gene_id),-c(1:2)]
rownames(expr) = resid.expr$ensembl_gene_id[!duplicated(resid.expr$ensembl_gene_id)]

cl = covariates$Status
names(cl) = covariates$ID
cl[cl == 'NCI'] = 'Control'
cl[cl == 'ND'] = 'Control'
cl[cl == 'SD'] = 'AD'
cl = cl[cl %in% c('Control','AD')] %>% droplevels 
cl.tmp = -as.numeric(cl)+2
names(cl.tmp) = names(cl)

origin = covariates$BrainRegion %>% as.numeric
names(origin) = covariates$ID
origin = origin[names(cl)]

expr = expr[, names(cl)]

rankprod.pfp = RPadvance(expr, cl.tmp, origin, num.perm = 100, gene.names = rownames(expr), plot=T, rand = 123456, huge=T)
rankprod.pval = apply(rankprod.pfp$pfp, 1, min) %>%
  rownameToFirstColumn('ensembl_gene_id') %>%
  dplyr::rename(rankprod.pval = DF)

metaAnal = join_all(list(min.pval, max.pval, fb.pval, rankprod.pval), type = 'full')
metaAnal$weight = -log10(metaAnal[,-c(1,6)]) %>% rowSums %>% rank
metaAnal = metaAnal %>% arrange(desc(weight))

writeLines('Number of genes differentially expressed between AD and control at an FDR of 0.05 are')
tmp = metaAnal %>% 
  dplyr::select(-weight) %>%
  gather(method, pval, -ensembl_gene_id) %>% 
  group_by(method) %>% 
  filter(pval <= 0.05) %>%
  dplyr::select(ensembl_gene_id) %>%
  unique %>%
  dlply(.(method), .fun = function(x){unique(x$ensembl_gene_id)})
kable(sapply(tmp, length) %>% as.data.frame)

tmp1 = Venn(tmp)

plotVenn3d(tmp1@IndicatorWeight[-(1),'.Weight'], labels = names(tmp))
```
### Heatmap of expression
```{r heatmap}
# Get the overlapping gene sets from all three methods
tmp.expr = t(scale(t(expr)))
tmp.expr = scale(tmp.expr)
tmp.expr = tmp.expr[intersect(intersect(tmp$fb.pval, tmp$min.pval), tmp$rankprod.pval),]

tmp.covariates = dplyr::select(covariates, BrainRegion, Status)
tmp.covariates$Status[tmp.covariates$Status == 'NCI'] = 'Control'
tmp.covariates$Status[tmp.covariates$Status == 'ND'] = 'Control'
tmp.covariates$Status[tmp.covariates$Status == 'SD'] = 'AD'
tmp.covariates = tmp.covariates %>% droplevels
rownames(tmp.covariates) = covariates$ID

h1 = HeatmapAnnotation(tmp.covariates)
Heatmap(tmp.expr, top_annotation = h1, show_row_names = F, show_column_names = F,
        show_row_dend = F, show_column_dend = F)
```

### Pathway enrichment analysis
```{r pathway.enrich}
setsToTest = diffexp %>%
  filter(adj.P.Val <= 0.05) %>%
  dlply(.(Tissue, Direction), .fun = function(x){
    unique(x$ensembl_gene_id)
  })

tmp1 = rankprod.pfp$pfp[intersect(intersect(tmp$fb.pval, tmp$min.pval), tmp$rankprod.pval),] <= 0.05
setsToTest$META.UP = rownames(tmp1)[which(tmp1[,1])]
setsToTest$META.DOWN = rownames(tmp1)[which(tmp1[,2])]

# Convert ensembl id to hgnc_symbols
setsToTest = lapply(setsToTest, function(x, Ensemble2HGNC){
  Ensemble2HGNC$hgnc_symbol[Ensemble2HGNC$ensembl_gene_id %in% x] %>%
    unique()
}, Ensemble2HGNC)

# Get Background genes
backgroundGenes = Ensemble2HGNC$hgnc_symbol[Ensemble2HGNC$ensembl_gene_id %in% rownames(expr)] %>% unique()

############################################################################################################
# Function to perform Fishers enrichment analysis
fisherEnrichment <- function(genesInSignificantSet, # A character vector of differentially expressed or some significant genes to test
                             genesInGeneSet, # A character vector of genes in gene set like GO annotations, pathways etc...
                             genesInBackground # Background genes that are 
){
  genesInSignificantSet = intersect(genesInSignificantSet, genesInBackground) # back ground filtering
  genesInNonSignificantSet = base::setdiff(genesInBackground, genesInSignificantSet)
  genesInGeneSet = intersect(genesInGeneSet, genesInBackground) # back ground filtering
  genesOutGeneSet = base::setdiff(genesInBackground,genesInGeneSet)
  
  pval = fisher.test(
    matrix(c(length(intersect(genesInGeneSet, genesInSignificantSet)),             
             length(intersect(genesInGeneSet, genesInNonSignificantSet)),
             length(intersect(genesOutGeneSet, genesInSignificantSet)),
             length(intersect(genesOutGeneSet, genesInNonSignificantSet))), 
           nrow=2, ncol=2), alternative="greater")
  OR = (length(intersect(genesInGeneSet, genesInSignificantSet)) * length(intersect(genesOutGeneSet, genesInNonSignificantSet))) / (length(intersect(genesInGeneSet, genesInNonSignificantSet)) * length(intersect(genesOutGeneSet, genesInSignificantSet))) %>% as.numeric()
  return(data.frame(pval = pval$p.value,
                    ngenes = length(genesInGeneSet),
                    noverlap = length(intersect(genesInGeneSet, genesInSignificantSet)),
                    Odds.Ratio = OR,
                    Genes = paste(intersect(genesInGeneSet, genesInSignificantSet), collapse = '|')))}
############################################################################################################

############################################################################################################
#### Get gene sets ####
# Download enrichr gene sets from synapse
GL_OBJ = synGet('syn4867851')
ALL_USED_IDs = c(ALL_USED_IDs, GL_OBJ$properties$id)
load(GL_OBJ@filePath)

gsets = c("BioCarta_2015", "GO_Biological_Process", "Reactome_2015", "TargetScan_microRNA", "WikiPathways_2015")
GeneSets.Enrichr = GeneSets[gsets]

# Download AD related gene sets from synapse
GL_OBJ = synGet('syn4893059');
ALL_USED_IDs = c(ALL_USED_IDs, GL_OBJ$properties$id)
load(GL_OBJ@filePath)

GeneSets.CM = list(CellTypeMarkers = GeneSets[grep('Zhang', names(GeneSets))],
                   AD = GeneSets['AD:GeneticLoci'])
GeneSets = c(GeneSets.Enrichr, GeneSets.CM)

# Filter gene list
GeneSets = filterGeneSets(GeneSets, backgroundGenes, minSize = 3, maxSize = 5000)

enrichResults = list()
for (name in names(setsToTest)){
  genesInModule = setsToTest[[name]]  
  enrichResults[[name]] = lapply(GeneSets,
                                    function(x, genesInModule, genesInBackground, fisherEnrichment, rownameToFirstColumn){
                                      tmp = as.data.frame(t(sapply(x, fisherEnrichment, genesInModule, genesInBackground)))
                                      tmp = rownameToFirstColumn(tmp,'GeneSetName')
                                      return(tmp)
                                    }, unique(genesInModule), unique(backgroundGenes), fisherEnrichment, rownameToFirstColumn) %>%
    rbindlist(use.names=TRUE, idcol = 'Category') %>%
    dplyr::mutate(fdr = p.adjust(pval, 'fdr'))
  writeLines(paste0('Completed ',name))  
}

# Write results to file
tmp1 = rbindlist(enrichResults, use.names = TRUE, idcol = 'ComparisonName', fill = TRUE) %>%
  filter(!is.na(Category))

tmp1$pval = unlist(tmp1$pval)
tmp1$ngenes = unlist(tmp1$ngenes)
tmp1$noverlap = unlist(tmp1$noverlap)
tmp1$Odds.Ratio = unlist(tmp1$Odds.Ratio)
tmp1$Genes = unlist(tmp1$Genes)

# Store logcpm in synapse
write.table(tmp1, file = 'enrich.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('enrich.tsv', 
           name = 'Pathway Enrichment Results (AD and Control)', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')
```

### Store results in synapse
```{r synapse.store, include=FALSE, cache=FALSE}
thisFileName <- 'MetaAnalysis.Rmd'

# Github link
thisRepo <- getRepo(repository = "th1vairam/Brain_Reg_Net", ref="branch", refName='metaAnal')
thisFile <- getPermlink(repository = thisRepo, repositoryPath=paste0('code/Rmd/',thisFileName))

# Store consolidated data in synapse
CODE = Folder(name = 'MetaAnalysis of Control vs AD Data', parentId = "syn5569102")
CODE = synStore(CODE)

# Store covariates in synapse
write.table(covariates, file = 'ALLCovariates.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('ALLCovariates.tsv', 
           name = 'Covariates', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')

# Store logcpm in synapse
write.table(logcpm, file = 'ALLLogCPM.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('ALLLogCPM.tsv', 
           name = 'Log CPM (AD and Control)', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')

# Store residual expression in synapse
write.table(expr, file = 'ALLExpr.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('ALLExpr.tsv', 
           name = 'Residual Expression (AD and Control)', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')

# Store diffexp in synapse
write.table(diffexp, file = 'ALLDiffExp.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('ALLDiffExp.tsv', 
           name = 'Differential Expression (AD and Control)', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')

# Store meta analysis in synapse
write.table(metaAnal, file = 'ALLMetaAnal.tsv', sep = '\t', row.names=F, quote=F)
OBJ = File('ALLMetaAnal.tsv', 
           name = 'Meta Analysis (AD and Control)', 
           parentId = CODE$properties$id)
OBJ = synStore(OBJ,
               used = as.character(c(covariates.id)),
               executed = thisFile,
               activityName = 'MetaAnalysis of AMP-AD reprocessed data')
```